-- Hindi content for bank_questions (question_text_hi, explanation_hi)
-- Batch: IDs 1301-1330 (30 rows). Human-authored; facts/names/dates preserved.
-- SAFE: updates ONLY the two _hi columns, only where question_text_hi is empty; no English/options/answers/ids touched.
SET NAMES utf8mb4;
START TRANSACTION;

UPDATE `bank_questions` SET `question_text_hi` = 'सिख परंपरा के अनुसार सिख धर्म की स्थापना किसने की?', `explanation_hi` = 'गुरु नानक को सिख परंपरा का संस्थापक माना जाता है।' WHERE `id` = 1301 AND (`question_text_hi` IS NULL OR `question_text_hi` = '');
UPDATE `bank_questions` SET `question_text_hi` = 'किस मराठा शासक ने पश्चिमी दक्कन को केंद्र बनाकर एक स्वतंत्र राज्य की स्थापना की?', `explanation_hi` = 'शिवाजी ने 17वीं शताब्दी में पश्चिमी दक्कन में एक स्वतंत्र मराठा राज्य की स्थापना की।' WHERE `id` = 1302 AND (`question_text_hi` IS NULL OR `question_text_hi` = '');
UPDATE `bank_questions` SET `question_text_hi` = 'शिवाजी का राज्याभिषेक 1674 में किस किले में हुआ था?', `explanation_hi` = 'शिवाजी का राज्याभिषेक 1674 में रायगढ़ में हुआ था।' WHERE `id` = 1303 AND (`question_text_hi` IS NULL OR `question_text_hi` = '');
UPDATE `bank_questions` SET `question_text_hi` = 'अपने राज्याभिषेक के समय शिवाजी ने औपचारिक रूप से कौन सी उपाधि धारण की?', `explanation_hi` = 'शिवाजी को छत्रपति की उपाधि से विभूषित किया गया, जो संप्रभु राजसत्ता का प्रतीक है।' WHERE `id` = 1304 AND (`question_text_hi` IS NULL OR `question_text_hi` = '');
UPDATE `bank_questions` SET `question_text_hi` = 'आठ मंत्रियों वाली कौन सी मराठा प्रशासनिक परिषद थी?', `explanation_hi` = 'शिवाजी का अष्टप्रधान आठ प्रमुख मंत्रियों की एक परिषद थी।' WHERE `id` = 1305 AND (`question_text_hi` IS NULL OR `question_text_hi` = '');
UPDATE `bank_questions` SET `question_text_hi` = 'शाहू के अधीन पहला पेशवा कौन था जिसने इस पद को अत्यधिक प्रभावशाली बनाया?', `explanation_hi` = 'बालाजी विश्वनाथ 1713 में पेशवा बने और शाहू की रिहाई के बाद मराठा शक्ति को सुदृढ़ करने में मदद की।' WHERE `id` = 1306 AND (`question_text_hi` IS NULL OR `question_text_hi` = '');
UPDATE `bank_questions` SET `question_text_hi` = 'कौन सा पेशवा तीव्र घुड़सवार अभियानों और उत्तर भारत की ओर विस्तार के लिए प्रसिद्ध है?', `explanation_hi` = 'बाजीराव प्रथम ने तीव्र और गतिशील घुड़सवार अभियानों के माध्यम से मराठा प्रभाव का तेज़ी से विस्तार किया।' WHERE `id` = 1307 AND (`question_text_hi` IS NULL OR `question_text_hi` = '');
UPDATE `bank_questions` SET `question_text_hi` = '1761 का पानीपत का तीसरा युद्ध मुख्यतः मराठों और किसके बीच लड़ा गया?', `explanation_hi` = 'मराठों ने 1761 में पानीपत में अहमद शाह अब्दाली की अफगान सेनाओं से युद्ध किया।' WHERE `id` = 1308 AND (`question_text_hi` IS NULL OR `question_text_hi` = '');
UPDATE `bank_questions` SET `question_text_hi` = '14वीं शताब्दी में अपने भाई बुक्का के साथ विजयनगर साम्राज्य की स्थापना किसने की?', `explanation_hi` = 'हरिहर प्रथम और बुक्का को परंपरागत रूप से 1336 में विजयनगर की स्थापना का श्रेय दिया जाता है।' WHERE `id` = 1309 AND (`question_text_hi` IS NULL OR `question_text_hi` = '');
UPDATE `bank_questions` SET `question_text_hi` = 'विजयनगर साम्राज्य की राजधानी कौन सा नगर था?', `explanation_hi` = 'तुंगभद्रा नदी के किनारे स्थित हम्पी साम्राज्य की राजधानी थी।' WHERE `id` = 1310 AND (`question_text_hi` IS NULL OR `question_text_hi` = '');
UPDATE `bank_questions` SET `question_text_hi` = 'कौन सा विजयनगर शासक अपनी सैन्य सफलताओं और साहित्य के संरक्षण के लिए प्रसिद्ध है?', `explanation_hi` = 'कृष्णदेवराय विजयनगर के सबसे शक्तिशाली शासकों में से एक और साहित्य के प्रमुख संरक्षक थे।' WHERE `id` = 1311 AND (`question_text_hi` IS NULL OR `question_text_hi` = '');
UPDATE `bank_questions` SET `question_text_hi` = 'कृष्णदेवराय के शासनकाल में किस विदेशी यात्री ने विजयनगर का विस्तृत विवरण लिखा?', `explanation_hi` = 'पुर्तगाली यात्री डोमिंगो पेस ने कृष्णदेवराय के शासनकाल में विजयनगर की समृद्धि का वर्णन किया।' WHERE `id` = 1312 AND (`question_text_hi` IS NULL OR `question_text_hi` = '');
UPDATE `bank_questions` SET `question_text_hi` = '1565 के तालीकोटा के युद्ध ने किस साम्राज्य को गंभीर रूप से कमज़ोर कर दिया?', `explanation_hi` = '1565 में तालीकोटा में विजयनगर की सेना की हार से उसकी राजधानी तबाह हो गई और साम्राज्यिक शक्ति का पतन हुआ।' WHERE `id` = 1313 AND (`question_text_hi` IS NULL OR `question_text_hi` = '');
UPDATE `bank_questions` SET `question_text_hi` = 'बीदर को एक महत्वपूर्ण राजधानी के रूप में स्थापित करने से कौन सा बहमनी शासक जुड़ा है?', `explanation_hi` = 'अहमद शाह वली ने बहमनी राजधानी को गुलबर्ग से बीदर स्थानांतरित किया।' WHERE `id` = 1314 AND (`question_text_hi` IS NULL OR `question_text_hi` = '');
UPDATE `bank_questions` SET `question_text_hi` = 'शिक्षा और स्थापत्य के संरक्षण के लिए प्रसिद्ध बहमनी सल्तनत का प्रसिद्ध फ़ारसी प्रशासक और मंत्री कौन था?', `explanation_hi` = 'महमूद गवां एक शक्तिशाली बहमनी मंत्री थे, जो प्रशासनिक सुधारों और विद्या के संरक्षण के लिए जाने जाते हैं।' WHERE `id` = 1315 AND (`question_text_hi` IS NULL OR `question_text_hi` = '');
UPDATE `bank_questions` SET `question_text_hi` = 'किस दक्कन राज्य पर कुतुब शाही वंश का शासन था और जिसका केंद्र गोलकोंडा था?', `explanation_hi` = 'कुतुब शाहियों ने पूर्वी दक्कन में गोलकोंडा सल्तनत पर शासन किया।' WHERE `id` = 1316 AND (`question_text_hi` IS NULL OR `question_text_hi` = '');
UPDATE `bank_questions` SET `question_text_hi` = 'मैसूर के वोडेयार वंश की स्थापना किसने की?', `explanation_hi` = 'यदुराय वोडेयार को परंपरागत रूप से मैसूर के वोडेयार वंश का संस्थापक माना जाता है।' WHERE `id` = 1317 AND (`question_text_hi` IS NULL OR `question_text_hi` = '');
UPDATE `bank_questions` SET `question_text_hi` = 'मैसूर का कौन सा शासक अंग्रेज़ों के विरुद्ध प्रतिरोध के लिए प्रसिद्ध हुआ और सेरिंगपट्टम में मारा गया?', `explanation_hi` = 'टीपू सुल्तान 1799 में सेरिंगपट्टम की रक्षा करते हुए अंग्रेज़ों के विरुद्ध लड़ते हुए मारे गए।' WHERE `id` = 1318 AND (`question_text_hi` IS NULL OR `question_text_hi` = '');
UPDATE `bank_questions` SET `question_text_hi` = 'टीपू सुल्तान की सेनाओं ने अंग्रेज़ों के विरुद्ध किस तकनीक का प्रभावी उपयोग किया?', `explanation_hi` = 'टीपू की सेनाओं ने उन्नत लोहे के आवरण वाले रॉकेटों का उपयोग किया, जिसने बाद में ब्रिटिश रॉकेट विकास को प्रभावित किया।' WHERE `id` = 1319 AND (`question_text_hi` IS NULL OR `question_text_hi` = '');
UPDATE `bank_questions` SET `question_text_hi` = 'शिवाजी की माता कौन थीं जिनका उनके पालन-पोषण पर महत्वपूर्ण प्रभाव रहा?', `explanation_hi` = 'शिवाजी की माता जीजाबाई को उनके पालन-पोषण और आदर्शों पर प्रभाव के लिए स्मरण किया जाता है।' WHERE `id` = 1320 AND (`question_text_hi` IS NULL OR `question_text_hi` = '');
UPDATE `bank_questions` SET `question_text_hi` = 'किस मराठा रानी ने अपने पति राजाराम की मृत्यु के बाद मुगलों के विरुद्ध प्रतिरोध का नेतृत्व किया?', `explanation_hi` = 'ताराबाई ने 18वीं शताब्दी के प्रारंभ में मुगल सेनाओं के विरुद्ध मराठा प्रतिरोध का नेतृत्व किया।' WHERE `id` = 1321 AND (`question_text_hi` IS NULL OR `question_text_hi` = '');
UPDATE `bank_questions` SET `question_text_hi` = 'किस राजपूत शासक ने हल्दीघाटी के युद्ध में अकबर की सेनाओं से युद्ध किया?', `explanation_hi` = 'मेवाड़ के महाराणा प्रताप ने 1576 में हल्दीघाटी में राजा मान सिंह के नेतृत्व वाली मुगल सेनाओं से युद्ध किया।' WHERE `id` = 1322 AND (`question_text_hi` IS NULL OR `question_text_hi` = '');
UPDATE `bank_questions` SET `question_text_hi` = 'हल्दीघाटी का युद्ध वर्तमान के किस राज्य में हुआ था?', `explanation_hi` = 'हल्दीघाटी राजस्थान के राजसमंद जिले में स्थित एक पर्वतीय दर्रा है।' WHERE `id` = 1323 AND (`question_text_hi` IS NULL OR `question_text_hi` = '');
UPDATE `bank_questions` SET `question_text_hi` = 'कुंभलगढ़ की किलेबंदी के निर्माण से कौन सा राजपूत शासक जुड़ा है?', `explanation_hi` = 'मेवाड़ के राणा कुंभा ने कुंभलगढ़ किले का विस्तार और सुदृढ़ीकरण किया।' WHERE `id` = 1324 AND (`question_text_hi` IS NULL OR `question_text_hi` = '');
UPDATE `bank_questions` SET `question_text_hi` = '14वीं शताब्दी में भारत की यात्रा के बाद \'रिहला\' नामक यात्रा-वृत्तांत किसने लिखा?', `explanation_hi` = 'इब्न बतूता के \'रिहला\' में उनकी यात्राओं का वर्णन है, जिसमें दिल्ली सल्तनत में बिताया गया उनका समय भी शामिल है।' WHERE `id` = 1325 AND (`question_text_hi` IS NULL OR `question_text_hi` = '');
UPDATE `bank_questions` SET `question_text_hi` = 'किस दिल्ली सुल्तान ने इब्न बतूता को क़ाज़ी नियुक्त किया?', `explanation_hi` = 'मुहम्मद बिन तुगलक ने इब्न बतूता को दिल्ली में न्यायाधीश नियुक्त किया।' WHERE `id` = 1326 AND (`question_text_hi` IS NULL OR `question_text_hi` = '');
UPDATE `bank_questions` SET `question_text_hi` = 'किस फ़ारसी विद्वान ने महमूद गजनवी के साथ यात्रा की और \'किताब-उल-हिंद\' लिखी?', `explanation_hi` = 'अल-बिरूनी ने \'किताब-उल-हिंद\' लिखी, जो भारतीय समाज, धर्म और विद्या का विश्लेषणात्मक विवरण है।' WHERE `id` = 1327 AND (`question_text_hi` IS NULL OR `question_text_hi` = '');
UPDATE `bank_questions` SET `question_text_hi` = '1025-26 में सोमनाथ मंदिर के विध्वंस से कौन सा शासक जुड़ा है?', `explanation_hi` = 'महमूद गजनवी ने 1025-26 में सोमनाथ पर आक्रमण किया।' WHERE `id` = 1328 AND (`question_text_hi` IS NULL OR `question_text_hi` = '');
UPDATE `bank_questions` SET `question_text_hi` = '1191 में तराइन के पहले युद्ध में मुहम्मद गोरी को किसने हराया?', `explanation_hi` = 'पृथ्वीराज चौहान ने 1191 में तराइन के पहले युद्ध में मुहम्मद गोरी को हराया।' WHERE `id` = 1329 AND (`question_text_hi` IS NULL OR `question_text_hi` = '');
UPDATE `bank_questions` SET `question_text_hi` = '1192 में तराइन के दूसरे युद्ध में पृथ्वीराज चौहान को किसने हराया?', `explanation_hi` = 'मुहम्मद गोरी ने 1192 में तराइन में पृथ्वीराज को हराया, जिससे उत्तर भारत में ग़ोरी विस्तार का मार्ग खुला।' WHERE `id` = 1330 AND (`question_text_hi` IS NULL OR `question_text_hi` = '');

COMMIT;
